export enum StoryType {
    'FETCH_STORY_NEW_CHAP' = 'FETCH_STORY_NEW_CHAP',
    'FETCH_STORY_NEW' = 'FETCH_STORY_NEW',
    'FETCH_STORY_RECOMMENDER' = 'FETCH_STORY_RECOMMENDER',
    'FETCH_STORY_COMPLETE' = 'FETCH_STORY_COMPLETE',
    'FETCH_STORY_HOT' = 'FETCH_STORY_HOT',
    'FETCH_STORY_UPDATE' = 'FETCH_STORY_UPDATE',
    'FETCH_STORY_RANK_DAY' = 'FETCH_STORY_RANK_DAY',
    'FETCH_GET_MENU' = 'FETCH_GET_MENU'
}